config/routes.rb
Rails.application.routes.draw do

  get '/:locale' => 'jobs#index', as: 'locale_root', constraints: { locale: /fr|en/ }
  root 'jobs#index'
  
  scope "(:locale)", locale: /fr|en/ do
    resources :jobs, except: :destroy do
      put 'activate', on: :member
    end
    resources :job_subscriptions, only: [:show, :create, :edit, :update, :destroy]
    resources :charges

    get 'terms'        => 'pages#terms'
    get 'privacy'      => 'pages#privacy'
    get 'contact',     to: 'messages#new', as: 'contact'
    post 'contact',    to: 'messages#create'
  end

end

app/models/job_subscription.rb
# Manage job subscriptions
class JobSubscription < ActiveRecord::Base
  before_validation :format_keywords
  before_create :set_next_sending, :set_last_sending

  validates_presence_of :email, :keywords, :frequency
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  scope :today, -> { where('DATE(next_sending) = ?', Date.today) }

  def set_next_sending
    self.next_sending = 
      if frequency == 1
        Time.now + 1.day
      elsif frequency == 2
        Time.now + 1.week
      else
        Time.now + 1.month
      end
  end

  private

  def set_last_sending
    self.last_sending = Time.now
  end

  def format_keywords
    return true unless keywords_changed?
    self.keywords = JSON.parse(keywords).join(' ').lstrip
    self.keywords = nil if self.keywords == ''
  end
end

app/controllers/job_subscriptions_controller.rb
# Manage job subscriptions
class JobSubscriptionsController < ApplicationController
  before_action :find_job_subscription, except: [:create]

  def create
    @job_subscription = JobSubscription.new(job_subscriptions_params)
    @job_subscription.locale = params[:locale]
    respond_to do |format|
      if @job_subscription.save
        flash.now[:success] = t('job_subscription.success', email: @job_subscription.email)
      else
        flash.now[:error] = t('job_subscription.error')
      end
      format.js
    end
  end

  def show
    redirect_to edit_job_subscription_path(@job_subscription)
  end

  def edit; end

  def update
    if @job_subscription.update_attributes(job_subscriptions_params)
      flash.now[:success] = t('job_subscription.update_success')
    else
      flash.now[:error] = t('job_subscription.update_failure')
    end
    render action: :edit
  end

  def destroy
    if @job_subscription.destroy
      flash[:success] = t('job_subscription.unsubscription_success')
      redirect_to locale_root_path
    else
      flash[:error] = t('job_subscription.unsubscription_failure')
      render action: :edit
    end
  end

  private

  def find_job_subscription
    @job_subscription = JobSubscription.find(params[:id])
  end

  def job_subscriptions_params
    params.require(:job_subscription).permit(:email, :city, :frequency, :last_sending, :next_sending, :locale, { :keywords => [] })
  end
end

app/views/job_subscriptions/_new.haml
.row#job_alert
  .columns.small-12
    %h6= t('job_subscription.title')

    #flash_message

    = form_for JobSubscription.new, auto_labels: false, remote: true do |f|
      = f.text_field :email, placeholder: 'Email'
      = f.select :keywords, Skills.all, {}, { class: 'tokenize-sample', multiple: 'multiple' }
      / = f.select :city, options_for_select([t("jobs.all_cities")] + Job.cities)
      = f.select :frequency, options_for_select([[t('job_subscription.daily'), 1], [t('job_subscription.weekly'), 2], [t('job_subscription.monthly'), 3]]), {}, { class: 'subscription_frequency' }
      = f.button type: 'submit', class: 'button expanded success', id: 'job_subscription_link' do
        %i.fa.fa-envelope-o
        = t('job_subscription.submit')

app/views/job_subscriptions/create.js.erb
$('#flash_message').html("<%= escape_javascript(render partial: 'shared/flash_messages') %>");
if ("<%= flash[:success] %>") {
  setTimeout(function() {
    $('#flash_message').html('');
    $('#animatedModal10').foundation('close');
  }, 5000);
}

app/views/job_subscriptions/edit.haml
- page_title t('title.job_subscription')
= render partial: 'shared/flash_messages'

.row#job_alert_edit
  .columns.small-12.medium-10.large-9.small-centered
    %h3#job_sub_edit_title= t('job_subscription.edit_title')
    = form_for @job_subscription, method: :put, auto_labels: false do |f|
      = f.text_field :email, placeholder: 'Email'
      / = f.text_field :keywords, class: 'alert_keywords', placeholder: t('keywords')
      = f.select :keywords, Skills.all, {}, { class: 'tokenize-sample', multiple: 'multiple', 'data-tokens' => @job_subscription.keywords }
      = f.select :city, options_for_select(Job.cities), prompt: t("jobs.all_cities")
      = f.select :frequency, options_for_select([[t('job_subscription.daily'), 1], [t('job_subscription.weekly'), 2], [t('job_subscription.monthly'), 3]])

      #job_sub_edit_links.text-right
        = link_to t('job_subscription.unsubscribe'), job_subscription_path(@job_subscription), method: :delete, class: 'button secondary hollow'
        = f.submit t('validate'), class: 'button success'