config/routes.rb
Rails.application.routes.draw do

  get '/:locale' => 'jobs#index', as: 'locale_root', constraints: { locale: /fr|en/ }
  root 'jobs#index'
  
  scope "(:locale)", locale: /fr|en/ do
    resources :jobs, except: :destroy do
      put 'activate', on: :member
    end
    resources :job_subscriptions, only: [:show, :create, :edit, :update, :destroy]
    resources :charges

    get 'terms'        => 'pages#terms'
    get 'privacy'      => 'pages#privacy'
    get 'contact',     to: 'messages#new', as: 'contact'
    post 'contact',    to: 'messages#create'
  end

end

app/models/job.rb
# Job model
class Job < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include FriendlyId
  friendly_id :slug_candidates, use: :slugged
  before_save :clean_up_technologies

  validates_presence_of :title, :city, :description, :company_name
  validates_presence_of :company_url, :company_mail, :postulation, if: :job_from_site?
  validates :company_mail, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, if: :job_from_site?

#   include PgSearch
#   pg_search_scope :search,
#                   against: {
#                     technologies:  'A',
#                     title:         'B',
#                     description:   'C',
#                     skills:        'D'# ,
# #                     company_about: 'D',
# #                     company_name:  'D',
# #                     city:          'D',
# #                     canton:        'D'
#                   },
#                   using: { tsearch: { any_word: true, dictionary: 'simple_syns_keywords' } }

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order('from_so, created_at DESC') }
  # scope :for_search, ->(search) { search(search) if search.present? }
  scope :for_city, ->(city) { where(city: city) if city.present? }
  scope :created_after, ->(datetime) {
    where('(from_so = ? AND created_at >= ?) OR (from_so = ? AND created_at >= ?)', true, datetime.beginning_of_day, false, datetime)
  }

  def self.for_search(search)
    return all if search.blank?
    search_terms = search.strip.split.compact.reject { |t| t == '' }
    if search_terms[0].casecmp('java') == 0
      query = "'#{search_terms[0]}' = ANY(technologies) OR title ilike '%#{search_terms[0]}(?!s|S)%' OR description ilike '%#{search_terms[0]}(?!s|S)%' OR skills ilike '%#{search_terms[0]}(?!s|S)%'"
    elsif search_terms[0].casecmp('c') == 0 || search_terms[0].casecmp('r') == 0
      query = "'#{search_terms[0]}' = ANY(technologies)"
    else
      query = "'#{search_terms.first}' = ANY(technologies) OR title ilike '%#{search_terms.first}%' OR description ilike '%#{search_terms.first}%' OR skills ilike '%#{search_terms.first}%'"
    end
    1.upto(search_terms.size - 1) do |i|
      if search_terms[i].casecmp('java') == 0
        query += " OR '#{search_terms[i]}' = ANY(technologies) OR title ilike '%#{search_terms[i]}(?!s|S)%' OR description ilike '%#{search_terms[i]}(?!s|S)%' OR skills ilike '%#{search_terms[i]}(?!s|S)%'"
      elsif search_terms[i].casecmp('c') == 0 || search_terms[i].casecmp('r') == 0
        query += " OR '#{search_terms[i]}' = ANY(technologies)"
      else
        query += " OR '#{search_terms[i]}' = ANY(technologies) OR title ilike '%#{search_terms[i]}%' OR description ilike '%#{search_terms[i]}%' OR skills ilike '%#{search_terms[i]}%'"
      end
    end if search_terms.size > 1
    where(query)
  end

  def self.cities
    active.pluck(:city).uniq.sort
  end

  def slug_candidates
    [
      [:title, :city],
      [:title, :city, :company_name],
      [:title, :city, :company_name, :id]
    ]
  end

  def job_from_site?
    !from_so
  end

  def safe_description
    return description.html_safe unless from_so
    description.gsub('</li><br />', '</li>').gsub('<br /><ul>', '<ul>').html_safe
  end

  def safe_skills
    return skills.html_safe unless from_so
    skills.gsub('</li><br />', '</li>').gsub('<br /><ul>', '<ul>').html_safe
  end

  def safe_about
    return company_about.html_safe unless from_so
    company_about.gsub('</li><br />', '</li>').gsub('<br /><ul>', '<ul>').html_safe
  end

  def days_from_creation
    return I18n.t('date.today') unless created_at
    I18n.l(created_at.to_date, format: :day_month_year_concise)
  end

  def salary
    return nil unless min_salary || max_salary
    if min_salary && !max_salary
      "CHF #{number_with_delimiter(min_salary)}"
    elsif max_salary && !min_salary
      "CHF #{number_with_delimiter(max_salary)}"
    else
      "CHF #{number_with_delimiter(min_salary)} - #{number_with_delimiter(max_salary)}"
    end
  end

  private

  def clean_up_technologies
    self.technologies = self.technologies.compact.reject { |t| t == "" }
  end
end

app/controllers/jobs_controller.rb
# Jobs management
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :activate]

  def index
    session[:search] = params[:search] if params[:search]
    session[:city] = params[:city] if params[:city]
    session[:city] = nil if params[:city] == 'all'

    # General search
    db_jobs = Job.active.for_city(session[:city]).for_search(session[:search]).ordered
    @jobs = db_jobs.page(params[:page]).per(20)
    respond_to do |format|
      format.html
      format.js
      format.json { paginate json: db_jobs, per_page: 20 }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @job }
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(jobs_params)
    if @job.save
      redirect_to job_path(@job)
    else
      flash.now[:error] = t('jobs.form.errors')
      render action: :new
    end
  end

  def edit; end

  def update
    if @job.update_attributes(jobs_params)
      redirect_to job_path(@job)
    else
      flash.now[:error] = t('jobs.form.errors')
      render action: :edit
    end
  end

  def activate
    # charge_error = nil
    # begin
    #   # Amount in cents
    #   @amount = 10000
    #
    #   customer = Stripe::Customer.create(
    #     email:  params[:stripeEmail],
    #     source: params[:stripeToken]
    #   )
    #
    #   charge = Stripe::Charge.create(
    #     customer:      customer.id,
    #     amount:        @amount,
    #     description:   I18n.t("jobs.payment_description"),
    #     currency:      'chf',
    #     receipt_email: @job.company_mail
    #   )
    #
    # rescue Stripe::CardError => e
    #   charge_error = e.message
    # end
    # if charge_error
    #   flash[:error] = charge_error
    #   render action: :edit
    # else
    #   @job.update_attributes(active: true)
    #   flash[:success] = I18n.t("jobs.successfully_created")
    #   # UserMailer.job_confirmation(@job.id).deliver
    #   redirect_to job_path(@job)
    # end

    if @job.update_attributes(active: true)
      flash[:success] = t('jobs.temp_successfully_created')
      JobConfirmationEmailWorker.new.perform(@job.id)
      redirect_to job_path(@job)
    else
      flash.now[:error] = t('jobs.form.errors')
      render action: :edit
    end
  end

  private

  def jobs_params
    params.require(:job).permit(
      :title, :description, :city, :canton, :remote, :min_salary, :max_salary,
      :postulation, :company_name, :company_url, :company_mail, :active,
      { :technologies => [] }, :skills, :company_about, :from_so
    )
  end

  def find_job
    @job = Job.friendly.find(params[:id])
  end
end

app/views/jobs/_job_details.haml
.row#job_details
  .columns.small-12
    - if job.description.present?
      %h5.description_title= t("jobs.description")
      = job.safe_description

    - if job.skills.present?
      %h5.section_title= t("jobs.skills")
      = job.safe_skills

    - if job.company_about.present?
      %h5.section_title= t("jobs.company_about")
      = job.safe_about

    - if job.company_url
      %p#company_website
        %b= t("jobs.company_website")
        \:
        = link_to job.company_url, "http://#{job.company_url}", title: job.company_url, target: "_blank"

.row#job_postulation
  .columns.small-7.medium-8
    %h6
      %b= t("jobs.interested")
    - if job.from_so
      = link_to t("jobs.so_contact"), job.so_url, target: "_blank"
    - else
      = job.postulation
  .columns.small-5.medium-4
    - if job.active and !job.from_so
      = social_share_button_tag(job.title)

.row
  .columns.small-12
    - if job.active
      = link_to t("back_home"), jobs_path, title: t('home'), class: "hollow button", id: "back_button"
    - else
      .row
        .columns.small-6
          = link_to t('validate'), activate_job_path(@job), method: :put, class: 'button expanded success'
        .columns.small-6
          = link_to t('edit'), edit_job_path(@job), class: 'button hollow expanded'

app/views/jobs/_job_form.haml
- page_title t('title.new_ad')
= render partial: 'shared/flash_messages'

.row
  .columns.small-12
    %p= t('jobs.form.info')

    = form_for job, auto_labels: false do |f|
      .row.job_form_section
        .columns.small-12.medium-9.large-9
          %h2.form_title= t('jobs.form.subtitle_1')
          = f.label :company_name, t('jobs.company_name')
          = f.text_field :company_name, placeholder: t('jobs.form.company_name_placeholder')

          = f.label :company_url, t('jobs.company_website')
          = f.text_field :company_url, placeholder: t('jobs.form.company_url_placeholder')

          = f.label :company_about_trix_input_job, t('jobs.company_about')
          = f.trix_editor :company_about, rows: 7
          %br

          = f.label :company_mail, t('jobs.company_mail')
          = f.text_field :company_mail, placeholder: t('jobs.form.company_mail_placeholder')

      .row.job_form_section
        .columns.small-12.medium-9.large-9
          %h2.form_title= t('jobs.form.subtitle_2')
          = f.label :title, t('jobs.title')
          = f.text_field :title, placeholder: t('jobs.form.title_placeholder')

          = f.label :city, t('jobs.city')
          = f.text_field :city, placeholder: t('jobs.form.city_placeholder')

          = f.label :canton, t('jobs.canton')
          = f.select :canton, Canton.all, prompt: t('canton.select')

          = f.check_box :remote, label: t('jobs.form.remote_placeholder')

          = f.label :min_salary, t('jobs.salary')
          .row
            .columns.small-6
              = f.text_field :min_salary, placeholder: t('jobs.form.min_salary_placeholder'), 'aria-describedby' => 'minSalaryHelpText'
              %p.help-text#minSalaryHelpText= t('jobs.form.min_salary_help')
            .columns.small-6
              = f.text_field :max_salary, placeholder: t('jobs.form.max_salary_placeholder'), 'aria-describedby' => 'maxSalaryHelpText'
              %p.help-text#maxSalaryHelpText= t('jobs.form.max_salary_help')

          = f.label :technologies, t('jobs.technologies')
          = f.select :technologies, Skills.all, {}, { class: 'tokenize-sample', multiple: 'multiple' }

          = f.label :description_trix_input_job, t('jobs.description'), id: 'description_label'
          = f.trix_editor :description, rows: 7
          %br
          = f.label :skills_trix_input_job, t('jobs.skills')
          = f.trix_editor :skills, rows: 7
          %br
          = f.label :postulation, t('jobs.postulation')
          = f.text_area :postulation, rows: 2, placeholder: t('jobs.form.postulation_placeholder')

        = render partial: 'job_form_help'
        
      .row
        .columns.small-12.medium-12.large-12
          = f.submit t('jobs.preview_button'), class: 'button expanded'

app/views/jobs/_job_form_help.haml
.columns.hide-for-small-only.medium-3.large-3
  #help_section
    .title_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.title_help")
    .salary_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.salary_help")
    .technologies_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.technologies_help")
    .description_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.description_help")
    .skills_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.skills_help")
    .company_about_help.callout.success.hide
      .row
        .columns.small-1
          %i.fa.fa-hand-o-left
        .columns.small-11
          %p= t("jobs.form.about_help")

app/views/jobs/_job_header.haml
.row#job_header
  .columns.small-12
    .row
      .columns.small-12
        %h3.title= job.title

    .row
      .columns.small-12
        = render partial: "job_subheader", locals: { job: job }

app/views/jobs/_job_subheader.haml
.job_subheader
  %span.company_name= job.company_name
  %span.job_location
    %i.fa.fa-map-marker
    = job.city
  - if job.salary
    %span.job_salary
      %i.fa.fa-credit-card
      = job.salary
  - if job.remote
    %span.job_remote
      %i.fa.fa-wifi
      = t('jobs.remote_authorized')

- if job.technologies.any?
  .job_categories
    - job.technologies.each do |techno|
      %span{ class: techno.present? ? 'job_category' : '' }= techno

app/views/jobs/_jobs_list.haml
%ul.no-bullet.joblist
  - @jobs.each do |job|
    %li{ 'data-link' => job_path(job) }
      .row
        .columns.small-12.medium-9.large-10
          %span.job_title= job.title
        .columns.hide-for-small-only.medium-3.large-2.text-right
          %span.job_date
            = job.days_from_creation
      .row
        .columns.small-12
          = render partial: 'job_subheader', locals: { job: job }

= paginate @jobs

:javascript
  $(document).ready(function(){
    $('li[data-link]').on('click', function() {
      window.location = $(this).data('link');
    });
  });

app/views/jobs/_no_results.haml
.row#no_search_results
  .columns.small-12.text-center
    %i.fa.fa-frown-o.fa-5x
    %h4= t('jobs.no_results.title')
    .row
      .columns.small-10.small-offset-1.medium-8.medium-offset-2.large-6.large-offset-3
        %p= t('jobs.no_results.info')
    
    

app/views/jobs/edit.haml
= render partial: "job_form", locals: { job: @job }

app/views/jobs/index.haml
.row
  .columns.small-12.medium-5.skills
    = select_tag :search, options_for_select(Skills.all), id: 'search', class: 'tokenize-sample', multiple: 'multiple', :'data-url' => jobs_path, :'data-value' => session[:search]
  .columns.small-12.medium-4
    = select_tag 'cities_select', options_for_select([t('jobs.all_cities')] + Job.cities, session[:city]), :'data-url' => jobs_path
  .columns.small-12.medium-3
    %a{ 'data-toggle' => 'animatedModal10', class: 'button success expanded', id: 'alert_button' }= t('job_subscription.submit')
    #animatedModal10.reveal{ 'data-reveal' => '', 'data-animation-out' => 'slide-out-down' }
      = render partial: 'job_subscriptions/new'
      %button.close-button{ 'aria-label' => 'Close reveal', 'data-close' => '', type: 'button' }
        %span{ 'aria-hidden' => 'true' } ×

.row
  .columns.small-12
    %hr
    #jobs_list
      - if @jobs.any?
        = render partial: 'jobs_list', locals: { jobs: @jobs }
      - else
        = render partial: 'no_results'

:javascript
  $(document).ready(function() {
    $('#cities_select').on("change", function() {
      if ($('#cities_select option:selected').text() == "#{t('jobs.all_cities')}") {
        city = 'all';
      } else {
        city = $('#cities_select option:selected').text();
      }
      $.ajax({
        url: $(this).data('url'),
        method: 'GET',
        dataType: 'script',
        data: { city: city },
        cache: true
      });
    });
  });

app/views/jobs/index.js.erb
<% if @jobs.any? %>
  $('#jobs_list').html("<%= escape_javascript(render partial: 'jobs_list', locals: { jobs: @jobs } ) %>");
<% else %>
  $('#jobs_list').html("<%= escape_javascript(render partial: 'no_results' ) %>");
<% end %>
$("#search").val("<%= session[:search] %>");

app/views/jobs/new.haml
- meta_description 'Publiez votre annonce et faites vous remarquer par les développeurs'
= render partial: "job_form", locals: { job: @job }

app/views/jobs/show.haml
- if @job.active
  - page_title t('title.show', job_title: @job.title)
- else
  - page_title t('title.preview')

- meta_description "#{strip_tags(@job.description[0..150])}..."

= render partial: 'shared/flash_messages'
= render partial: 'job_header', locals: { job: @job }
= render partial: 'job_details', locals: { job: @job }
      
/ %script.stripe-button{ "data-allow-remember-me" => "false","data-amount" => "10000", "data-currency" => "chf", "data-description" => I18n.t('jobs.payment'), "data-key" => Rails.configuration.stripe[:publishable_key], "data-label" => I18n.t('jobs.payment_button'), "data-locale" => params[:locale], "data-name" => "Swiss IT Jobs", "data-email" => @job.company_mail, :src => "https://checkout.stripe.com/checkout.js" }
   
// :javascript
//   if ("#{!@job.active}") {
//     $('.stripe-button-el').hide();
//   }