config/routes.rb
Rails.application.routes.draw do

  get '/:locale' => 'jobs#index', as: 'locale_root', constraints: { locale: /fr|en/ }
  root 'jobs#index'
  
  scope "(:locale)", locale: /fr|en/ do
    resources :jobs, except: :destroy do
      put 'activate', on: :member
    end
    resources :job_subscriptions, only: [:show, :create, :edit, :update, :destroy]
    resources :charges

    get 'terms'        => 'pages#terms'
    get 'privacy'      => 'pages#privacy'
    get 'contact',     to: 'messages#new', as: 'contact'
    post 'contact',    to: 'messages#create'
  end

end

app/views/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52776623-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_flash_messages.haml
- if flash[:error].present?
  .row
    .columns.small-12
      .alert.callout{ "data-closable" => "" }
        %p= flash[:error]
        %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
          %span{"aria-hidden" => "true"} ×

- if flash[:notice].present?
  .row
    .columns.small-12
      .success.callout{ "data-closable" => "" }
        %p= flash[:notice]
        %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
          %span{"aria-hidden" => "true"} ×

- if flash[:success].present?
  .row
    .columns.small-12
      .success.callout{ "data-closable" => "" }
        %p= flash[:success]
        %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
          %span{"aria-hidden" => "true"} ×

app/views/shared/_footer.haml
#feedback
  .row
    .columns.small-12
      %p
        = t('sidebar.feedback_question')
        = link_to t('sidebar.feedback_link'), contact_path
        = t('sidebar.feedback_help')

#footer
  .row
    .columns.small-12
      .menu
        %span= link_to t('pages.contact'), contact_path, title: t('pages.contact')
        \|
        %span= link_to t('pages.terms'), terms_path, title: t('pages.terms')
        \|
        %span= link_to t('pages.privacy'), privacy_path, title: t('pages.privacy')
      .social
        %span
          = link_to 'https://twitter.com/swissitjob', target: '_blank', title: 'Twitter' do
            %i.fa.fa-twitter
        %span
          = link_to 'https://plus.google.com/+SwissitjobCh', target: '_blank', title: 'Google plus' do
            %i.fa.fa-google-plus

app/views/shared/_top_bar.haml
.top-bar
  .row
    .columns.small-12
      .top-bar-title
        %span{ 'data-hide-for' => 'medium', 'data-responsive-toggle' => 'responsive-menu' }
          %button.menu-icon{ 'data-toggle' => '', type: 'button' }
        = link_to 'SWISS IT JOB', locale_root_url, title: t('home'), id: 'site_title'
      #responsive-menu
        .top-bar-left
          %ul.dropdown.menu{ 'data-dropdown-menu' => '' }
            %li= link_to t('jobs.new'), new_job_path, title: t('jobs.new'), class: 'button'
        .top-bar-right
          %ul.menu#lang-menu
            %li= link_to 'FR', locale: 'fr'
            %li= link_to 'EN', locale: 'en'